### ISSUE TITLE
[Feature Request] Playlist Directory & Support Playlist Files

### ISSUE THREAD

**Issue by trymeouteh** [AdrienPoupa/VinylMusicPlayer#99] opened 2019-01-02 01:38 UTC
Please allow Vinyl to be able to choose a directory on the phone where it can find playlist files and use them in the app. Please support m3u and wpl playlists.

Many music players have built-in app playlist that are not files but are saved within the app but this is not a good option since these playlist cannot be backed up and cannot be transferred or synced across devices. Since Vinyl Music Player is a basic music player which requires the user to manage their music files it will not too hard for the users to manage playlist files. This is also handy when you have multiple android devices like a phone and tablet and the ability to easily copy a playlist file from device to device.

Please support absolute path and relative paths in playlists.

**Comment by GeoZac** [comment] 2019-01-02 03:58
Duplicate of #100

**Comment by trymeouteh** [comment] 2019-01-02 16:43
This is not a duplicate of #100. This is about playlist files and choosing a playlist directory. #100 is about smart playlists.

**Closed** 2019-04-12 20:26 UTC
Labels: feature request
