### ISSUE TITLE
songs not getting added to any playlist created including favs

### ISSUE THREAD

**Issue by shahedk2326** [AdrienPoupa/VinylMusicPlayer#540] opened 2021-11-24 21:13 UTC
**Describe the bug**
songs not getting added to any playlist created including favs

**To Reproduce**
1. Go to the song currently playing or in the library
2. Click on the three dots
3. Scroll down to add to playlist and click on it or tap on the fav button
4. Check the playlist created and its blank

**Expected behavior**
songs should be getting added to playlists created

**Smartphone :**
 - Device: sm-j730f
 - Android Version:10
 - ROM: lineage os 17.1
 - Vinyl Music Player Version: 1.3.0

**Additional context**
the cause might be that the songs are getting added from external storage

**Comment by hxd2772** [comment] 2021-11-25 14:44
what kind of file are you trying to add?

**Comment by shahedk2326** [comment] 2021-11-27 08:36
mp3

**Comment by hxd2772** [comment] 2021-11-27 09:35
I add songs to playlist from external storage and it work s. What type of SD card are you using?

**Comment by shahedk2326** [comment] 2021-11-27 16:31
nothing special

**Comment by soncaokim** [comment] 2021-12-28 10:40
This looks like a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248 which has no resolution.
The workaround is to have songs moved to internal storage

**Closed by soncaokim** 2021-12-28 10:40 UTC
