### ISSUE TITLE
Album year display randomly truncated

### ISSUE THREAD

**Issue by Vrihub** [AdrienPoupa/VinylMusicPlayer#195] opened 2019-09-13 20:59 UTC
(minor bug)
Occasionally, when selecting an artist, in the horizontally-scrollable album covers parade the years below some of the albums are displayed truncated, as "196...", "197...", or even "2004..." etc. Sometimes when you scroll the album list to the right and go back to the first albums, the bug disappears and the year is displayed correctly.

This happens quite randomly: i.e. not for all artists, not always for the same artist, not for all albums of an artist; sometimes the scroll-and-scroll-back fix works, sometimes it doesn't...

**Comment by soncaokim** [comment] 2020-01-23 20:38
This looks like a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/169 - I havent figured it out.

**Closed** 2020-01-24 00:19 UTC
Labels: bug
