### ISSUE TITLE
Media files will not be scanned

### ISSUE THREAD

**Issue by dev4223** [AdrienPoupa/VinylMusicPlayer#132] opened 2019-04-03 11:21 UTC
When I try to scan files or folders the app gives the message to scan but there are no entries in the library. 

-

Device info:
---
<table>
<tr><td>App version</td><td>0.20.1</td></tr>
<tr><td>App version code</td><td>162</td></tr>
<tr><td>Android build version</td><td>203C432R1</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>CLT-L29 9.0.0.203(C432E5R1P9)</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWCLT</td></tr>
<tr><td>Device model</td><td>CLT-L29</td></tr>
<tr><td>Device product name</td><td>CLT-L29</td></tr>
<tr><td>Device hardware name</td><td>kirin970</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment] 2019-04-09 01:23
Duplicate of #94

**Closed by AdrienPoupa** 2019-04-09 01:23 UTC
Labels: bug
