### ISSUE TITLE
[bug] Album Arts Not Displaying on Songs/ Albums/ Now Playing Views

### ISSUE THREAD

**Issue by tbartlett17** [AdrienPoupa/VinylMusicPlayer#452] opened 2021-05-21 18:16 UTC
**Describe the bug**
On the Songs tab, Albums tab, Now Playing view, and the Artist page showing all albums from that artist, song album art does  not show or load properly and instead shows the default gray circle placeholder art as if there was no album art to display. I know that most of my music files have all metadata including artworks and the artwork is displaying correctly in the default music player but not on Vinyl Music Player.

**Expected behavior**
The song and Album arts should display properly on all these views. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/36083073/119179377-b0eee500-ba23-11eb-8835-10d8016526ea.png" alt="Vinyl Albums View - No Art" width="256"> <img src="https://user-images.githubusercontent.com/36083073/119179431-bea46a80-ba23-11eb-89ec-710fa7401832.png" alt="Default Music App Albums View - Shows Art" width="256">
<img src="https://user-images.githubusercontent.com/36083073/119179384-b2201200-ba23-11eb-865e-1f655cd5bf71.png" alt="Vinyl Artist-Albums View - No Art" width="256"> <img src="https://user-images.githubusercontent.com/36083073/119179437-c106c480-ba23-11eb-93f5-83e1b65e45ed.png" alt="Default Music App Artist-Albums View - Shows Art" width="256">
<img src="https://user-images.githubusercontent.com/36083073/119179408-b9472000-ba23-11eb-8f3b-e3499668e986.png" alt="Vinyl Now Playing View - No Art" width="256"> <img src="https://user-images.githubusercontent.com/36083073/119179455-c401b500-ba23-11eb-8402-c670f2ec370e.png" alt="Default Music App Now Playing View - Shows Art" width="256">
<img src="https://user-images.githubusercontent.com/36083073/119179420-bba97a00-ba23-11eb-9114-3819ffae53ec.png" alt="Vinyl Songs View - No Art" width="256"> <img src="https://user-images.githubusercontent.com/36083073/119179456-c5cb7880-ba23-11eb-8cd5-019b483c0b69.png" alt="Default Music App Songs View - Shows Art" width="256">

**Smartphone (please complete the following information):**
 - Device: OnePlus 5T
 - Android Version: 11
 - ROM: Lineage OS 18.1
 - Vinyl Music Player Version: 1.2.0

**Additional context**
The music files are primarily .flac and .mp3 formats.
The Vinyl Music Player app was downloaded through the F-Droid app.
The art used to display just fine a long time ago, but i am not sure when it stopped functioning correctly. I think it was working when i was back on Android 9, Lineage OS 16.1 but cannot say whether changing to a new rom/android version introduced the issue or if it was an app update that introduced the issue.

**Comment by soncaokim** [comment] 2021-05-21 18:49
Is it possible to attach a sample file, so that I can have a look?

**Comment by tbartlett17** [comment] 2021-05-21 19:36
It doesn't look like I can upload .flac files directly to GitHub so [here is a link to a couple .flac files](https://drive.google.com/drive/folders/1BXHDaFPhcAmk8z4i_VedjTDzqiZZCZmR?usp=sharing) I posted to my Google Drive.

**Comment by soncaokim** [comment] 2021-05-21 22:12
Cover image looks okay here

![Screenshot_20210522-001049~2](https://user-images.githubusercontent.com/13333482/119203006-5d67b000-ba92-11eb-834c-d330658367ce.jpg)

**Comment by tbartlett17** [comment] 2021-05-25 15:28
Any thoughts then for what I may try to do to fix this on my device?

**Comment by soncaokim** [comment] 2021-05-25 19:07
Hi Tyler,
Because of the lack of factual info, I cannot make any comment. If you are able to pull your device log and share it here, I can have a detailed analysis.

(Since you are adventurous enough to use LineageOS, I guess you would be familiar with application logging and development processes.)

**Comment by tbartlett17** [comment] 2021-05-25 19:50
Attached is the device log after restarting the device and then opening Vinyl, playing music and navigating to different views inside the app. 
[logcat.txt](https://github.com/AdrienPoupa/VinylMusicPlayer/files/6541960/logcat.txt)

**Comment by soncaokim** [comment] 2021-05-25 20:30
Thanks for the quick turn around. I ve briefly looked at the log, despite the fact that you've gone to an album detail view (showing the list of associated songs and supposedly the missing cover image), there is no evident log stating the failure of loading the cover.

I will need time to compare the log, and probably need your cooperation again.

--

If you can reproduce a log with approximate time when you open the album detail page with the missing cover, that'll help me to focus on the bug.

**Comment by tbartlett17** [comment] 2021-05-26 01:19
I have put together a list of the approximate start and end times of the different pages I was on. Times are probably +- 3 seconds.
Here you go:
<table>
<thead>
<tr>
<th>Page</th>
<th>Time</th>
</tr>
</thead>
<tr>
<td>Now Playing</td>
<td>17:45:48 -- 17:46:30</td>
</tr>
<tr>
<td>Songs</td>
<td>17:44:44 -- 17:45:45</td>
</tr>
<tr>
<td>Albums</td>
<td>17:46:44 -- 17:47:25</td>
</tr>
<tr>
<td>Album Details (for Urban Flora)</td>
<td>17:47:25 -- 17:47:55</td>
</tr>
<tr>
<td>Artists</td>
<td>17:47:56 -- 17:49:00</td>
</tr>
<tr>
<td>Artist Details (all albums/songs by Avenged Sevenfold)</td>
<td>17:49:02 -- 17:49:42</td>
</tr>
</table>

logcat generated in the Termux app at 17:53:35.
[logcat.txt](https://github.com/AdrienPoupa/VinylMusicPlayer/files/6543173/logcat.txt)

**Comment by soncaokim** [comment] 2021-05-30 19:04
Tyler, just to tell you that I havent had time to look at this yet.

**Comment by tbartlett17** [comment] 2021-05-30 19:43
Thanks for the heads up. No rush on it. Let me know if there is anything else I can provide to help.

**Comment by tbartlett17** [comment] 2021-06-01 01:54
I hit the "Rescan Library" button in the slide out menu and its fixed all the album arts. Not sure if you still want to look into this or not but at the very least the issue for me personally has been fixed.

**Comment by soncaokim** [comment] 2021-06-01 20:32
Thanks for updating. I will close this issue.

**Closed by soncaokim** 2021-06-01 20:32 UTC
Labels: bug
