### ISSUE TITLE
Genre Tab Empty

### ISSUE THREAD

**Issue by ehrdan** [AdrienPoupa/VinylMusicPlayer#8] opened 2018-02-01 15:15 UTC
All other parts of the library seem to populate appropriately, but nothing shows up in the genre tab/section.

**Comment by AdrienPoupa** [comment] 2018-02-01 15:32
It takes a while, but eventually populates for me

**Comment by AdrienPoupa** [comment] 2018-02-01 15:32
![screenshot_20180201-103155](https://user-images.githubusercontent.com/15086425/35686844-42d66c8a-073b-11e8-841f-2961a4301a5a.png)

**Comment by ehrdan** [comment] 2018-02-01 21:56
In still not seeing anything. Tried resetting library by adding music
folder to blacklist and then removing from same. Here is my device data:
Device info:
---
<table>
<tr><td>App version</td><td>0.16.4.4</td></tr>
<tr><td>App version code</td><td>150</td></tr>
<tr><td>Android build
version</td><td>US_Phone-14.14.1711.92-20171208</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build
ID</td><td>NRD90M.US_Phone-14.14.1711.92-20171208</td></tr>
<tr><td>Device brand</td><td>asus</td></tr>
<tr><td>Device manufacturer</td><td>asus</td></tr>
<tr><td>Device name</td><td>ASUS_X008_1</td></tr>
<tr><td>Device model</td><td>ASUS_X008DC</td></tr>
<tr><td>Device product name</td><td>US_Phone</td></tr>
<tr><td>Device hardware name</td><td>mt6735</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment] 2018-02-16 23:55
I'm unable to reproduce with my two devices. Closing this for now, feel free to reopen if you can track it further.

**Closed by AdrienPoupa** 2018-02-16 23:55 UTC
