### ISSUE TITLE
Filename not displayed by default if no title 

### ISSUE THREAD

**Issue by Tsurayaki** [AdrienPoupa/VinylMusicPlayer#294] opened 2020-09-25 17:19 UTC
**Describe the bug**
If the music doesn't have a title in music details (metadata) the filename is not displayed

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android release version: 10
 - Android build version: 2007191452
 - Android SDK version: 29
 - Vinyl Music Player Version: 0.24.0

![Screenshot_20200925-185901 1](https://user-images.githubusercontent.com/14942516/94296731-9a12f400-ff63-11ea-98d2-8bf63aa45174.jpg)

![Screenshot_20200925-191416 1](https://user-images.githubusercontent.com/14942516/94296804-b878ef80-ff63-11ea-9c99-96141116d6dd.jpg)

**Comment by sersorrel** [comment] 2020-09-26 21:44
This is happening for me with album titles since a very recent update.

**Comment by AdrienPoupa** [comment] 2020-09-30 23:39
@soncaokim I was able to trace the regression back to your discography change.

Could you please review that?

**Comment by AdrienPoupa** [comment] 2020-10-01 00:31
OK, I identified the issue. This should be a fairly easy fix.

As soon as it's there, I'll publish a new release and let you know.

Thanks for the report!

**Comment by AdrienPoupa** [comment] 2020-10-01 16:51
Fixed in 0.24.1

**Closed by AdrienPoupa** 2020-10-01 16:51 UTC
Labels: bug, reproduced

**Comment by vespadj** [comment] 2020-10-10 12:38
We waiting for 0.24.1 on F-Droid (last build is 0.24.0)

**Comment by vespadj** [comment] 2020-10-12 21:16
Out now 0.24.1 on F-Droid!
