### ISSUE TITLE
Albums are split into multiple albums

### ISSUE THREAD

**Issue by sersorrel** [AdrienPoupa/VinylMusicPlayer#328] opened 2020-10-21 12:03 UTC
**Describe the bug**
Since a recent update, many of my albums are split up into multiple ones based on the track artist. For example, [one](https://c418.bandcamp.com/album/one) is split into four displayed albums: one by C418, one by disco, one by Laura Shigihara, and one by Nifflas.

This album is currently formed of MP3s, with ID3v2.3 tags. I've tagged them using Kid3; the files are all in the same folder on the filesystem, and the album tag is set identically on each track. The artist tag is set to either `C418` or e.g. `Nifflas|C418` (which is Kid3's syntax for including multiple values in the same tag). Converting the tags to ID3v2.4 does not appear to change how Vinyl behaves.

In Vinyl's tag editor, the artist of the songs with multiple artists is currently just shown as e.g. `Nifflas`.

#292 looks wildly suspicious, but I don't currently have the time to bisect this and find out for sure, sorry.

**To Reproduce**
(I will try and find the time to tag some music I can redistribute in a way which demonstrates this problem in a bit)

**Expected behavior**
Proper multiple-artist support is already tracked in #207, but I would at least expect that tracks with identical TALB tags and which live in the same folder on the filesystem to be displayed in the same album.

**Screenshots**
![image](https://user-images.githubusercontent.com/9433472/96716691-472f2f80-139d-11eb-944d-132855bc35ef.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android Version: 11
 - ROM: stock
 - Vinyl Music Player Version: 1.0.0

**Comment by soncaokim** [comment] 2020-10-21 12:29
Hi, thanks for the details.
I'm closing this since it looks like a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/323

The comment https://github.com/AdrienPoupa/VinylMusicPlayer/issues/323#issuecomment-713073782 gives the current status.

**Closed by soncaokim** 2020-10-21 12:29 UTC
Labels: bug
