### ISSUE TITLE
Tracks appear twice in library but only one of them can be played

### ISSUE THREAD

**Issue by steinhmor** [AdrienPoupa/VinylMusicPlayer#313] opened 2020-10-11 13:23 UTC
**Describe the bug**
Every track on my SD-Card is shown twice in my library but only every second track is playable so that every playlist stops after one track and I have to tswitch manual to the next track. This happens with ogg, mp3 and flac and it seems like the error also is in phonograph... Resetting the data of the app and scanning the folder again didn't fix it. The unplayable tracks show only the Title and the duration as tag-details but nothing more. In some cases the playable Tracks show the filename and the unplayable the correct title from the tag.

**To Reproduce**
1. Add tracks to library
2. They appear twice

**Expected behavior**
A Track should only appear once in the library and unplayable tracks should be skipped automatically.

**Screenshots**
![Screenshot_20201011-151932_Vinyl_Music_Player](https://user-images.githubusercontent.com/11630531/95679816-958e4280-0bd5-11eb-8a17-b1f34dfb79fb.png)
![Screenshot_20201011-151923_Vinyl_Music_Player](https://user-images.githubusercontent.com/11630531/95679818-96bf6f80-0bd5-11eb-8ca0-8ed1a889264f.png)
![Screenshot_20201011-151949_Vinyl_Music_Player](https://user-images.githubusercontent.com/11630531/95679819-97580600-0bd5-11eb-9ec5-532d1cf50240.png)
![Screenshot_20201011-151941_Vinyl_Music_Player](https://user-images.githubusercontent.com/11630531/95679820-97580600-0bd5-11eb-9ac7-b947d6e8ce57.png)

**Smartphone (please complete the following information):**
 - Device: Fairphone 2
 - Android Version: Android 9
 - ROM: /e/ 0.11
 - Vinyl Music Player Version: 0.24.1

**Comment by soncaokim** [comment] 2021-01-29 22:16
Duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/315

**Closed by soncaokim** 2021-01-29 22:16 UTC
Labels: bug
