### ISSUE TITLE
[Feature request] Use subsonic api

### ISSUE THREAD

**Issue by frandavid100** [AdrienPoupa/VinylMusicPlayer#91] opened 2018-10-28 19:07 UTC
I have just discovered Vinyl, and I'd like to use it to listen to the music I uploaded to Funkwhale. I could do that if it could use the subsonic protocol.

**Comment by AdrienPoupa** [comment] 2019-04-08 14:02
Duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/42

**Closed by AdrienPoupa** 2019-04-08 14:02 UTC
