### ISSUE TITLE
Scan But No Media Appears?

### ISSUE THREAD

**Issue by grravity** [AdrienPoupa/VinylMusicPlayer#217] opened 2019-12-30 04:19 UTC
If I go to the music dir in the app, scan the dir, it scans through my 600 or so files, says completed, I go back to library and nothing new shows.
If I try to click a song through dir view, it says "xx - xx is not listed in the media store" and gives me the option to scan it. If I scan, then try to play it, it keeps saying the same thing. 

Basically I can't get any of my music listed in the apo, or really even play it for that matter. It did seem to detect two songs on my internal drive so maybe it's because this music is on the sd card?

**Comment by Oblivinati** [comment] 2020-01-04 08:55
Vinyl version : 0.22.1 (play store version)
OS : Pie 9.0
Devices : Nokia 8.1
Can replicate this issue

**Comment by Z3ROGRAV1TYx** [comment] 2020-01-05 00:37
Woops I didn't realize I forgot info.
OS: Pie
Device: LGv40
Version: I forget because I uninstalled, but it was the latest F-Droid release.

**Comment by Oblivinati** [comment] 2020-01-14 10:23
This bug appears to be an issue when naming the folder containing music on the SD card as "Music". Changing the folder name, restarting the device and rescanning the directory appears to be a workaround of the bug. Not sure if this fix will work on all devices, but it does work on mine as above.

**Comment by kivanctezoren** [comment] 2020-02-09 10:01
I had this issue with a folder in which I accidentally put a .nomedia file. Removing the file and rebooting solved it. I also use /Music/ as my music directory but I haven't encountered any other instances of this problem.

**Comment by soncaokim** [comment] 2020-08-29 08:22
I cannot reproduce this, I'm guessing that this fixed by this https://github.com/AdrienPoupa/VinylMusicPlayer/commit/14ad7af26ab7cbc8b27949b16f051b5bcc0f60c7 

I'm closing this bug report, @grravity @RastalDev Please dont hesitate to reopen.

**Closed by soncaokim** 2020-08-29 08:22 UTC
