### ISSUE TITLE
Android 10/Cannot add to favorites or to a playlist on a SDCard

### ISSUE THREAD

**Issue by ghost** [AdrienPoupa/VinylMusicPlayer#248] opened 2020-06-13 12:32 UTC
**Describe the bug**
I cannot add any song to a playlist or to favorites 

**To Reproduce**
1. Click on the add to favorites button or add to playlist button

**Comment by Atalonica** [comment] 2020-08-26 21:41
Same here.
Possible error:
`java.io.FileNotFoundException: /storage/ABCD-EFG/Music/.../file.mp3: open failed: EACCES (Permission denied)`

**Comment by patgdev** [comment] 2020-09-06 17:47
I have exactly the same problem. 

* Device: Galaxy S9
* Android Version: 10
* Version: 0.23.1 from Google Play

**Comment by AdrienPoupa** [comment] 2020-09-06 19:45
Are you using a SD card?

**Comment by patgdev** [comment] 2020-09-06 19:47
Yes, I do.

**Comment by soncaokim** [comment] 2020-09-28 20:03
Possible relevant stack trace: 

```
W/System.err: android.app.RecoverableSecurityException: com.poupa.vinylmusicplayer.ci.debug has no access to content://media/external_primary/audio/media/188
        at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:197)
        at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:194)
        at android.os.Parcel.readParcelable(Parcel.java:2973)
        at android.os.Parcel.createException(Parcel.java:2066)
W/System.err:     at android.os.Parcel.readException(Parcel.java:2039)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.bulkInsert(ContentProviderNative.java:503)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1909)
        at com.poupa.vinylmusicplayer.util.PlaylistsUtil.addToPlaylist(PlaylistsUtil.java:135)
        at com.poupa.vinylmusicplayer.util.PlaylistsUtil.addToPlaylist(PlaylistsUtil.java:107)
        at com.poupa.vinylmusicplayer.service.MusicService.playNextSong(MusicService.java:456)
        at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.playNextSong(MusicPlayerRemote.java:143)
        at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerPlaybackControlsFragment.lambda$setUpPrevNext$1(CardPlayerPlaybackControlsFragment.java:175)
        at com.poupa.vinylmusicplayer.ui.fragments.player.card.-$$Lambda$CardPlayerPlaybackControlsFragment$RGCsZG-vghQuH0xg5IaDV5IWssg.onClick(Unknown Source:0)
        at android.view.View.performClick(View.java:7125)
W/System.err:     at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/Choreographer: Skipped 646 frames!  The application may be doing too much work on its main thread.
V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
    cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/MediaPlayer: Use of stream types is deprecated for operations other than volume control
W/MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/AudioManager: Use of stream types is deprecated for operations other than volume control
    See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/System.err: java.io.FileNotFoundException: /storage/emulated/0/Download/Shania Twain/Star Of Wonder/11 White Christmas.mp3: open failed: EACCES (Permission denied)
W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at org.jaudiotagger.audio.AudioFile.checkFilePermissions(AudioFile.java:218)
        at org.jaudiotagger.audio.mp3.MP3File.<init>(MP3File.java:440)
W/System.err:     at org.jaudiotagger.audio.mp3.MP3FileReader.read(MP3FileReader.java:39)
        at org.jaudiotagger.audio.AudioFileIO.readFile(AudioFileIO.java:288)
        at org.jaudiotagger.audio.AudioFileIO.read(AudioFileIO.java:151)
W/System.err:     at com.poupa.vinylmusicplayer.util.MusicUtil.getLyrics(MusicUtil.java:399)
        at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(CardPlayerFragment.java:306)
W/System.err:     at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(CardPlayerFragment.java:295)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)
W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
W/System.err:     at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7255)
        at libcore.io.IoBridge.open(IoBridge.java:482)
    	... 15 more
```

**Comment by soncaokim** [comment] 2020-09-28 20:24
I can confirm that this is reproducible on Android 10 emulator with latest code (master, version 0.24.0).

**Comment by soncaokim** [comment] 2020-09-28 20:37
@AdrienPoupa The stack trace above https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248#issuecomment-700251819 is obtained by adding `ignored.printStackTrace();` to https://github.com/AdrienPoupa/VinylMusicPlayer/blob/54b4924044dab1eaf2b053117de580b92cc6c073/app/src/main/java/com/poupa/vinylmusicplayer/util/PlaylistsUtil.java#L144

Looks like Android 10 does some change on this and is now more restrictive. I havent gone through the docs nor stackoverflow, if you have any idea please share.

**Comment by soncaokim** [comment] 2020-10-04 12:25
I close this since PR 298 proposes a fix. Please dont hesitate to reopen if it's still not ok.

**Comment by patgdev** [comment] 2020-10-16 21:44
I have upgraded to Version 1.0, but the problem still exists on my device.

**Comment by soncaokim** [comment] 2020-10-16 22:32
I just did a fresh reinstall of version 1.0 and after granting the access + finish the initial scan, I can add/remove songs from the faves.

Last resort (I know this is not ideal, just want to know where the problem can be):
If you can afford losing the play history+preferences, can you please uninstall/reinstall the app and see if it still persist.

I'm reopening the issue for the time being

**Comment by patgdev** [comment] 2020-10-17 09:45
Thank you for the quick reply!

I removed and reinstalled the app and after granting the permission I did a couple of test scenarios: 

1. Adding a song to the favourites by clicking on the heart symbol while the song is playing
2. Using the options (the 3 dots) next to a title and adding the song to: 
2.1 a new playlist
2.2 an existing playlist

After all test cases I was still not able add or remove songs to a playlist or the favourites. :-(

However, I remembered the following comment: https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248#issuecomment-687882423

Consequently, I copied one title from my sd card to the local storage and did a retest. 
This time all described test cases worked!

Therefore, the bug is related to songs that are stored on the sd card.

**Comment by soncaokim** [comment] 2020-10-17 10:05
Thanks for the test.

**Comment by soncaokim** [comment] 2020-10-19 19:13
My bad, looks like my test was not complete since did not include the move to SD card.

Just did a quick Google search, and the perspective is not very rosy: https://issuetracker.google.com/issues/147619577

**Comment by wchen342** [comment] 2020-11-13 21:53
Just in case anyone is looking for a solution, I found a workaround (not a solution for the player but a very hacky way to make it work temporarily). To do it you will need:

- rooted Android 10
- Magisk module Systemizer and busybox
- ADB connection to a PC
- Knowledge about linux file systems and mount points

Systemization of Vinyl is not absolutely necessary, it can probably work without this.

Here is what I did:

1. Use systemizer to move Vinyl into `\system\priv-apps` and reboot.
2. ADB to your phone as go to root (`adb shell` then `su`)
3. Use `mount` to find out where is your SDCard actually mounted. In my case it is `/dev/block/vold/public:170,1`.
4. Go to `/storage/emulated/0` and create 2 folders. Let's call them `A` and `B`.
5. Bind mount the block device to `A` (`mount -o bind /dev/block/vold/public:170,1 A`).
6. **Important**: mount `A` to `B` with type `sdcardfs` (`mount -t sdcardfs A B`).
7. Go to Vinyl, go to Folder - select /sdcard/B as starting folder - rescan library.
8. After the rescan finishes you shall be able to add songs to playlists normally.

**Comment by ChrisMrX** [comment] 2020-11-15 15:54
I have exactly the same problem.
Add any song to a playlist or to favorites work correctly on internal storage but don't work on SD Card.

**Comment by soncaokim** [comment] 2020-12-14 20:13
As stated in https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248#issuecomment-712385424, looks like we are stuck for the moment. The only workaround (not a satisfactory one) that I can confirm is to move songs to internal storage.

**Closed** 2021-04-21 21:14 UTC
Labels: bug, reproduced, wontfix

**Comment by WaldoTheRanger** [comment] 2023-04-25 05:25
It strikes me as very odd that the history and top tracks playlists function fine with songs on the SD card

Why is it that the only problem is with manually added songs?

**Comment by WaldoTheRanger** [comment] 2023-04-25 06:52
No idea if this will be helpful in the end or not, but Retro music player works fine in this regard:
https://github.com/RetroMusicPlayer/RetroMusicPlayer

It appears to potentially work via workaround that saves the playlist to just the app, and not the media store, as it doesn't import the playlists created through this method correctly when you reinstall/install another app that should be able to import them
