### ISSUE TITLE
0.16.5.1  force closes on launch 

### ISSUE THREAD

**Issue by david0rk** [AdrienPoupa/VinylMusicPlayer#27] opened 2018-04-27 06:27 UTC
The app repeatedly closes. I was able to get it to run a bit longer by clearing all of the apps storage, but once I launched it and gave it permission to access files on my phone it went right back to crashing over and over.
Submitted feedback via android. 

Hardware- pixel 2xl

**Comment by AdrienPoupa** [comment] 2018-04-27 12:58
Hi!
Thanks for the report and sorry about that.
I noticed an issue with the 0.16.5, so I published the 0.16.5.1 right away after that, and that fixed it - at least for my phone.

Do you confirm that it's happening with the latest version on the play store? If yes, would you have some logs so I can reproduce it? Thanks!

**Comment by GeoZac** [comment] 2018-04-27 14:41
@AdrienPoupa Probably duplicate of https://github.com/kabouzeid/Phonograph/issues/476

**Comment by AdrienPoupa** [comment] 2018-04-27 18:18
Sorry about that :/

Feel free to reopen if need be

**Closed by AdrienPoupa** 2018-04-27 18:18 UTC
