### ISSUE TITLE
Support for multiple genres

### ISSUE THREAD

**Issue by kaeza** [AdrienPoupa/VinylMusicPlayer#70] opened 2018-08-15 18:35 UTC
My request is to split the genre tag at semicolons and show the given song in all genres.

From <https://www.blisshq.com/music-library-management-blog/2011/03/12/multiple-genres-in-mp3s/>:

>MP3s (or rather, the ID3 tagging format used by MP3s) don't support multiple tags for genre. Instead you must use the one existing tag and use a delimiter character to separate the genres within that tag. If your music tagger supports multiple genres, it will add the genres separated by the delimiter for you. If it doesn't you can always do it manually by manually adding the delimiter.
>
>What delimiter should be used? The de facto standard most music players adopt is to use the semi-colon character. For instance, your genre tag should appear as so:
>
>     GENRE = Rock;Shoegazing;Alternative
>
>Alternatives are suggested in the ID3v2.4 specifications. The former suggests forward slashes '/' although this stands a good chance of clashing with genre names with slashes in them! The latter suggests 'null' separators that may be hard to type. I suggest going with semi-colons.

**Comment by kaeza** [comment] 2018-08-15 18:44
￼

**Comment by Cantuariensis** [comment] 2020-08-15 09:33
Duplicate of #207, which is more detailed.

@AdrienPoupa @soncaokim Can you close this one?

**Closed** 2020-08-16 12:43 UTC
Labels: feature request
