### ISSUE TITLE
Some albums don't show realease year

### ISSUE THREAD

**Issue by quaeched** [AdrienPoupa/VinylMusicPlayer#72] opened 2018-09-05 13:13 UTC
In case of some albums, in the tag editor I can see the "Year" specified, however it does not show in album details. Only shows <b>-</b> under album name in artist section and <b>0</b> next to calendar icon under album duration in album section.

**Comment by AdrienPoupa** [comment] 2018-09-09 16:53
Should be fixed by new version, if not feel free to reopen https://github.com/AdrienPoupa/VinylMusicPlayer/commit/e507c57eb6a9c22c30c7a3d7c1c44921c0859680

**Comment by somehowwentverywrong1** [comment] 2020-01-23 12:56
This still happens: but it's always a - for me

**Comment by soncaokim** [comment] 2020-01-23 21:18
I can confirm this (never paid attention before). WIll have a look when I have time.

**Comment by soncaokim** [comment] 2020-01-23 22:56
Well, looks like the Android's MediaStore (maintained by the Android OS and from where the metadata information is pulled) always provide year=0.

The reason why in the tag editor we see the right value *would be* because in such places we use another library to pull the information directly from the mp3 file

**Comment by soncaokim** [comment] 2020-01-23 23:05
@AdrienPoupa Some debug code here, in the case you can confirm this on your side: https://github.com/soncaokim/VinylMusicPlayer/tree/album-year-display

**Closed** 2020-09-14 22:58 UTC

**Comment by alphanerdgen** [comment] 2022-08-15 14:44
@soncaokim @AdrienPoupa 

Please reopen this issue as it hasn't been fixed.

Proof:

![SS1](https://user-images.githubusercontent.com/83120103/184656974-82ca80f6-2dc3-49b9-b1a8-eba75e51c284.png)

![SS2](https://user-images.githubusercontent.com/83120103/184657019-bf3ef443-36be-4551-bb31-830897a7cff5.png)
