### ISSUE TITLE
App crashes when going to the next track

### ISSUE THREAD

**Issue by gianmarcogg03** [AdrienPoupa/VinylMusicPlayer#620] opened 2022-10-28 12:21 UTC
**Describe the bug**
When I'm playing an album, sometimes the app will crash a few seconds after going to the next track.

**To Reproduce**
1. Play an album
2. Wait for a few tracks
3. See if it happens, try maybe going to another app or locking the device

**Expected behavior**
The track should continue playing just fine.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6a
 - Android Version: 13 (TP1A.221005.003)
 - ROM: GrapheneOS
 - Vinyl Music Player Version: 1.3.0 (117)

**Additional context**
I always use my Google Pixel Buds A-Series with the app, although I don't think it affects its functionality at all.

**Comment by gaycodegal** [comment] 2023-01-18 21:09
I also have run into a similar problem.

1. Open app
1. Press shuffle
1. Press power to lock phone screen
1. Hit next song twice
1. Wait
1. App crash

I will look into fixing this bug myself I have a vague idea that there is a foreground process rule being hit here due to some like Android 12-13 upgrade restrictions on media apps

**Comment by gaycodegal** [comment] 2023-01-18 21:10
I'm pretty sure my Android 12 phone had no issue with this but since my trigger is consistent I'm hoping I should be able to easily debug this when I have the time

**Comment by soncaokim** [comment] 2023-01-18 22:45
If you can reproduce this consistently, and manage to capture the stack trace, I'd be interested.

About the Android foreground service, please be aware that I've fixed one - long standing and might be related - recently in my fork: https://github.com/vinyl2-team/vinyl2/pull/8

**Comment by gaycodegal** [comment] 2023-01-19 20:15
I can reproduce it consistently, it crashes every time for me following my steps.

```
2023-01-19 15:10:12.820 1268-1667/? I/ActivityManager: Killing 4833:com.poupa.vinylmusicplayer/u0a336 (adj 905): remove task
2023-01-19 15:10:12.905 14055-14055/? I/MediaPlayerList: onMediaKeyEventSessionChanged: packageName=com.poupa.vinylmusicplayer
2023-01-19 15:10:12.905 14055-14055/? W/MediaPlayerList: com.poupa.vinylmusicplayer is already the active player
2023-01-19 15:10:12.905 14055-14055/? W/AudioMediaPlayerWrapper: The session was destroyed com.poupa.vinylmusicplayer
2023-01-19 15:10:12.905 14055-14055/? D/MediaPlayerList: sessionUpdatedCallback(): packageName: com.poupa.vinylmusicplayer
2023-01-19 15:10:12.905 14055-14055/? D/MediaPlayerList: Removing media player com.poupa.vinylmusicplayer
2023-01-19 15:10:12.906 1268-1367/? I/WindowManager: WIN DEATH: Window{5d9c233 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity}
2023-01-19 15:10:12.906 1268-1367/? W/InputManager-JNI: Input channel object '5d9c233 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity (client)' was disposed without first being removed with the input manager!
2023-01-19 15:10:12.915 1268-1693/? W/UsageStatsService: Unexpected activity event reported! (com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity event : 23 instanceId : 130944142)
2023-01-19 15:10:37.724 1268-3625/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.poupa.vinylmusicplayer/.ui.activities.MainActivity bnds=[851,796][1058,1121]} from uid 10203
2023-01-19 15:10:37.747 1268-2285/? D/CoreBackPreview: Window{742fecb u0 Splash Screen com.poupa.vinylmusicplayer}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@e12b5c1, mPriority=0}
2023-01-19 15:10:37.750 1268-1698/? I/ActivityManager: Start proc 5876:com.poupa.vinylmusicplayer/u0a336 for next-top-activity {com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity}
2023-01-19 15:10:37.775 5876-5876/? D/nativeloader: Configuring classloader-namespace for other apk /data/app/~~QdMZXNdghLEYrLgoAuqONg==/com.poupa.vinylmusicplayer-cZ5Iy2FPnvFKPF8wMpC44g==/base.apk. target_sdk_version=29, uses_libraries=, library_path=/data/app/~~QdMZXNdghLEYrLgoAuqONg==/com.poupa.vinylmusicplayer-cZ5Iy2FPnvFKPF8wMpC44g==/lib/arm64, permitted_path=/data:/mnt/expand:/data/user/0/com.poupa.vinylmusicplayer
2023-01-19 15:10:37.778 5876-5876/? V/GraphicsEnvironment: ANGLE Developer option for 'com.poupa.vinylmusicplayer' set to: 'default'
2023-01-19 15:10:37.778 5876-5876/? V/GraphicsEnvironment: ANGLE GameManagerService for com.poupa.vinylmusicplayer: false
2023-01-19 15:10:37.821 5876-5876/? W/Resources: Drawable com.poupa.vinylmusicplayer:drawable/above_shadow has unresolved theme attributes! Consider using Resources.getDrawable(int, Theme) or Context.getDrawable(int).
    java.lang.RuntimeException
        at android.content.res.Resources.getDrawable(Resources.java:908)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.<init>(Unknown Source:296)
        at com.sothree.slidinguppanel.SlidingUpPanelLayout.<init>(Unknown Source:1)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at com.poupa.vinylmusicplayer.databinding.SlidingMusicPanelLayoutBinding.inflate(Unknown Source:4)
        at com.poupa.vinylmusicplayer.databinding.SlidingMusicPanelLayoutBinding.inflate(Unknown Source:2)
        at com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.createSlidingMusicPanel(Unknown Source:4)
        at com.poupa.vinylmusicplayer.ui.activities.MainActivity.createContentView(Unknown Source:18)
        at com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.onCreate(Unknown Source:3)
        at com.poupa.vinylmusicplayer.ui.activities.MainActivity.onCreate(Unknown Source:0)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8269)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-01-19 15:10:37.869 1268-1367/? D/CoreBackPreview: Window{31afc33 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@3ea3569, mPriority=0}
2023-01-19 15:10:37.874 1268-3625/? D/MediaSessionService: Media button session is changed to com.poupa.vinylmusicplayer/VinylMusicPlayer (userId=0)
2023-01-19 15:10:37.876 14055-14055/? I/MediaPlayerList: Adding wrapped media player: com.poupa.vinylmusicplayer at key: 4
2023-01-19 15:10:37.876 14055-14055/? I/MediaPlayerList: onMediaKeyEventSessionChanged: token=com.poupa.vinylmusicplayer
2023-01-19 15:10:37.877 14055-14055/? D/MediaPlayerList: setActivePlayer(): setting player to com.poupa.vinylmusicplayer
2023-01-19 15:10:37.878 14055-14055/? D/MediaPlayerList: onActiveSessionsChanged: controller: com.poupa.vinylmusicplayer
2023-01-19 15:10:37.878 14055-14055/? D/MediaPlayerList: Already have a controller for the player: com.poupa.vinylmusicplayer, updating instead
2023-01-19 15:10:37.924 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:37.924 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:37.924 4885-4885/? V/MusicFXControlPanelEffect: closeSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4601)
2023-01-19 15:10:37.925 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:37.925 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:37.940 1268-1664/? I/ActivityTaskManager: Displayed com.poupa.vinylmusicplayer/.ui.activities.MainActivity: +212ms
2023-01-19 15:10:38.035 3098-3098/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():1877 onStartInput(EditorInfo{inputType=0x0(NULL) imeOptions=0x0 privateImeOptions=null actionName=UNSPECIFIED actionLabel=null actionId=0 initialSelStart=-1 initialSelEnd=-1 initialCapsMode=0x0 hintText=null label=null packageName=com.poupa.vinylmusicplayer fieldId=-1 fieldName=null extras=null}, false)
2023-01-19 15:10:38.305 1268-5215/? D/CoreBackPreview: Window{742fecb u0 Splash Screen com.poupa.vinylmusicplayer EXITING}: Setting back callback null
2023-01-19 15:10:38.305 1268-2285/? W/InputManager-JNI: Input channel object '742fecb Splash Screen com.poupa.vinylmusicplayer (client)' was disposed without first being removed with the input manager!
2023-01-19 15:10:39.674 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:39.674 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:39.676 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:39.676 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:39.699 14055-14055/? V/AudioMediaPlayerWrapper: onPlaybackStateChanged(): com.poupa.vinylmusicplayer : PlaybackState {state=2, position=0, buffered position=0, speed=1.0, updated=272268028, actions=823, custom actions=[Action:mName='Cycle repeat mode, mIcon=2131230891, mExtras=null, Action:mName='Toggle shuffle mode, mIcon=2131230900, mExtras=null, Action:mName='Toggle favorite, mIcon=2131230858, mExtras=null], active item id=-1, error=null}
2023-01-19 15:10:39.701 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:39.703 1268-5215/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10336/5876 AA=USAGE_MEDIA/CONTENT_TYPE_MUSIC clientId=android.media.AudioManager@6bf5217com.poupa.vinylmusicplayer.service.MusicService$1@f432604 callingPack=com.poupa.vinylmusicplayer req=1 flags=0x0 sdk=29
2023-01-19 15:10:39.735 14055-14055/? V/AudioMediaPlayerWrapper: onPlaybackStateChanged(): com.poupa.vinylmusicplayer : PlaybackState {state=3, position=0, buffered position=0, speed=1.0, updated=272268059, actions=823, custom actions=[Action:mName='Cycle repeat mode, mIcon=2131230891, mExtras=null, Action:mName='Toggle shuffle mode, mIcon=2131230900, mExtras=null, Action:mName='Toggle favorite, mIcon=2131230858, mExtras=null], active item id=-1, error=null}
2023-01-19 15:10:39.736 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:39.796 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:39.829 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:39.843 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:40.098 2236-2236/? D/MediaResumeListener: Checking for service component for com.poupa.vinylmusicplayer
2023-01-19 15:10:40.103 2236-2275/? D/MediaResumeListener: Testing if we can connect to ComponentInfo{com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.service.MusicService}
2023-01-19 15:10:40.103 2236-2236/? D/MediaResumeListener: Checking for service component for com.poupa.vinylmusicplayer
2023-01-19 15:10:40.110 2236-2275/? D/MediaResumeListener: Testing if we can connect to ComponentInfo{com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.service.MusicService}
2023-01-19 15:10:40.213 2236-2275/? E/MediaBrowser: onConnectFailed for ComponentInfo{com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.service.MusicService}
2023-01-19 15:10:40.214 2236-2275/? D/ResumeMediaBrowser: Connection failed for ComponentInfo{com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.service.MusicService}
2023-01-19 15:10:40.214 2236-2275/? E/MediaResumeListener: Cannot resume with ComponentInfo{com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.service.MusicService}
2023-01-19 15:10:43.391 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:43.392 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:43.394 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:43.394 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:43.413 14055-14055/? V/AudioMediaPlayerWrapper: onPlaybackStateChanged(): com.poupa.vinylmusicplayer : PlaybackState {state=2, position=0, buffered position=0, speed=1.0, updated=272271743, actions=823, custom actions=[Action:mName='Cycle repeat mode, mIcon=2131230891, mExtras=null, Action:mName='Toggle shuffle mode, mIcon=2131230900, mExtras=null, Action:mName='Toggle favorite, mIcon=2131230858, mExtras=null], active item id=-1, error=null}
2023-01-19 15:10:43.421 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:43.423 1268-3625/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10336/5876 AA=USAGE_MEDIA/CONTENT_TYPE_MUSIC clientId=android.media.AudioManager@6bf5217com.poupa.vinylmusicplayer.service.MusicService$1@f432604 callingPack=com.poupa.vinylmusicplayer req=1 flags=0x0 sdk=29
2023-01-19 15:10:43.449 14055-14055/? V/AudioMediaPlayerWrapper: onPlaybackStateChanged(): com.poupa.vinylmusicplayer : PlaybackState {state=3, position=0, buffered position=0, speed=1.0, updated=272271775, actions=823, custom actions=[Action:mName='Cycle repeat mode, mIcon=2131230891, mExtras=null, Action:mName='Toggle shuffle mode, mIcon=2131230900, mExtras=null, Action:mName='Toggle favorite, mIcon=2131230858, mExtras=null], active item id=-1, error=null}
2023-01-19 15:10:43.454 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:43.573 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:44.319 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:44.319 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:44.321 4885-4885/? V/MusicFXControlPanelReceiver: Package name: com.poupa.vinylmusicplayer
2023-01-19 15:10:44.321 4885-4885/? V/MusicFXControlPanelEffect: openSession(android.app.ReceiverRestrictedContext@28e9ef7, com.poupa.vinylmusicplayer, 4609)
2023-01-19 15:10:44.347 14055-14055/? V/AudioMediaPlayerWrapper: onPlaybackStateChanged(): com.poupa.vinylmusicplayer : PlaybackState {state=2, position=0, buffered position=0, speed=1.0, updated=272272674, actions=823, custom actions=[Action:mName='Cycle repeat mode, mIcon=2131230891, mExtras=null, Action:mName='Toggle shuffle mode, mIcon=2131230900, mExtras=null, Action:mName='Toggle favorite, mIcon=2131230858, mExtras=null], active item id=-1, error=null}
2023-01-19 15:10:44.352 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:44.354 1268-5124/? I/MediaFocusControl: requestAudioFocus() from uid/pid 10336/5876 AA=USAGE_MEDIA/CONTENT_TYPE_MUSIC clientId=android.media.AudioManager@6bf5217com.poupa.vinylmusicplayer.service.MusicService$1@f432604 callingPack=com.poupa.vinylmusicplayer req=1 flags=0x0 sdk=29
2023-01-19 15:10:44.379 14055-14055/? V/AudioMediaPlayerWrapper: onPlaybackStateChanged(): com.poupa.vinylmusicplayer : PlaybackState {state=3, position=0, buffered position=0, speed=1.0, updated=272272707, actions=823, custom actions=[Action:mName='Cycle repeat mode, mIcon=2131230891, mExtras=null, Action:mName='Toggle shuffle mode, mIcon=2131230900, mExtras=null, Action:mName='Toggle favorite, mIcon=2131230858, mExtras=null], active item id=-1, error=null}
2023-01-19 15:10:44.384 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:44.413 14055-14055/? V/AudioMediaPlayerWrapper: trySendMediaUpdate(): Metadata has been updated for com.poupa.vinylmusicplayer
2023-01-19 15:10:51.433 5876-5876/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.poupa.vinylmusicplayer, PID: 5876
    java.lang.IllegalStateException: Animator has already started, cannot change it now!
        at android.graphics.animation.RenderNodeAnimator.checkMutable(RenderNodeAnimator.java:138)
        at android.graphics.animation.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:314)
        at android.graphics.animation.RenderNodeAnimator.setDuration(RenderNodeAnimator.java:37)
        at android.animation.AnimatorSet.updateAnimatorsDuration(AnimatorSet.java:774)
        at android.animation.AnimatorSet.getTotalDuration(AnimatorSet.java:1744)
        at android.animation.AnimationHandler.lambda$new$0$android-animation-AnimationHandler(AnimationHandler.java:224)
        at android.animation.AnimationHandler$$ExternalSyntheticLambda0.doFrame(Unknown Source:2)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
        at android.view.Choreographer.doCallbacks(Choreographer.java:899)
        at android.view.Choreographer.doFrame(Choreographer.java:827)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-01-19 15:10:51.441 1268-3509/? W/ActivityTaskManager:   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.MainActivity
2023-01-19 15:10:51.555 1268-2285/? I/ActivityManager: Process com.poupa.vinylmusicplayer (pid 5876) has died: fg +50 FGS 
2023-01-19 15:10:51.555 1268-3509/? I/WindowManager: WIN DEATH: Window{31afc33 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity}
2023-01-19 15:10:51.556 1268-3509/? W/InputManager-JNI: Input channel object '31afc33 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity (client)' was disposed without first being removed with the input manager!
2023-01-19 15:10:51.557 14055-14055/? I/MediaPlayerList: onMediaKeyEventSessionChanged: packageName=com.poupa.vinylmusicplayer
2023-01-19 15:10:51.557 14055-14055/? W/MediaPlayerList: com.poupa.vinylmusicplayer is already the active player
2023-01-19 15:10:51.558 14055-14055/? W/AudioMediaPlayerWrapper: The session was destroyed com.poupa.vinylmusicplayer
2023-01-19 15:10:51.558 14055-14055/? D/MediaPlayerList: sessionUpdatedCallback(): packageName: com.poupa.vinylmusicplayer
2023-01-19 15:10:51.559 14055-14055/? D/MediaPlayerList: Removing media player com.poupa.vinylmusicplayer
2023-01-19 15:10:51.564 1268-1693/? W/UsageStatsService: Unexpected activity event reported! (com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity event : 23 instanceId : 148573838)
```

**Comment by soncaokim** [comment] 2023-01-19 20:25
In the latest email, there are two exceptions in the log:
- theming stuff: is this a show stopper? I guess not, I do see this as well
but not preventing the app.
- animator is already started: i can confirm having this app crash as well,
but not reproducible 100%. Only on Android 13. And I still dont know
exactly where the the trouble is.

**Comment by gaycodegal** [comment] 2023-01-19 20:37
Based on the crash timing I'm pretty sure it's the `IllegalStateException: Animator has already started, cannot change it now!` that causes the crash. The drawable thing can be ignored for now, app seems to survive that just fine. I'll take a look into the source code tonight and see if I can find the specific line that's leading to this crash, since it is so reproducible on my device.

**Comment by gaycodegal** [comment] 2023-01-23 02:08
thanks for the patience, life is busy. The specific line causing the crash is:

`animatorSet.setDuration(ViewUtil.VINYL_MUSIC_PLAYER_ANIM_TIME);`, line 453 in CardPlayerFragment.java

commenting out this line fixes the issue (obviously causes visual glitches I assume), but prevents the app from crashing.

figured out that this would be the issue from: https://stackoverflow.com/questions/45419378/disabling-animations-on-a-device-crashes-the-app

**Comment by gaycodegal** [comment] 2023-01-23 02:12
replacing that line with 

```Java
            for (Animator animator : animatorSet.getChildAnimations()){
                animator.setDuration(ViewUtil.VINYL_MUSIC_PLAYER_ANIM_TIME);
            }

```

seems to work as far as I can tell. Presumably if there are any other `AnimatorSet`s in use in the app, they will have this issue too.

**Comment by gaycodegal** [comment] 2023-01-23 02:38
this bug has a fair amount of impact in the app, as you can see by the complaints above. I would recommend making a minor version 1.4.1 release for this fix, although it's entirely your call, and as with all things you may want to spend time using the debug version of the app and seeing if this causes any issues, but as far as I can reckon, this should be a safe fix

**Comment by soncaokim** [comment] 2023-01-23 08:29
thanks, I'll have a look

**Closed** 2023-01-25 06:31 UTC
Labels: bug
