### ISSUE TITLE
Support multiple artists/genres/etc. in ID3 tags

### ISSUE THREAD

**Issue by lukas-kasticky** [AdrienPoupa/VinylMusicPlayer#207] opened 2019-10-30 15:39 UTC
**Is your feature request related to a problem? Please describe.**
Many songs of my MP3 library have ID3 tags with multiple artists and genres - separated with `; `. In Vinyl they show up as one artist/genre. Here's an example from the artist page (the song by Eminem and Rihanna doesn't show up on Eminem's artist page):

![Example](https://coinsh.red/u/Vinyl_Artists.jpg)

**Describe the solution you'd like**
Vinyl should detect songs with multiple artists/genres and add the songs to the individual artists/genres. Other tags are probably affected as well. I've read that multiple entries could be seperated by `;`, `/` or some null character

**Comment by Cantuariensis** [comment] 2020-03-15 14:42
Hi lukas-kasticky,
Great idea, I'd love to see multiples artists and genres like that!
Latest version of Windows Media Player was using `;` to separate genres.
Thanks

**Comment by Cantuariensis** [comment] 2020-08-15 10:14
This feature request at Phonograph, in case things are moving there:
https://github.com/kabouzeid/phonograph-issue-tracker/issues/236
https://github.com/kabouzeid/Phonograph/issues/791
https://github.com/kabouzeid/Phonograph/issues/151

Some people claim here and there that the only Android players implementing multiple genres and artists are [GoneMAD](https://play.google.com/store/apps/details?id=gonemad.gmmp&hl=en), [MediaMonkey](https://play.google.com/store/apps/details?id=com.ventismedia.android.mediamonkey&hl=en_US), and [BlackPlayer](https://play.google.com/store/apps/details?id=com.musicplayer.blackplayerfree&hl=en). I tried all of them with `; `, `/ `, and `\\` separator (this last one is creating 2 "Artist" or "Genre" entries when used in Mp3tag). None of them work properly 😔

I'm afraid we are out of luck, except if that feature is added to the MediaStore database (which I doubt in this era of music streaming).

**Comment by AdrienPoupa** [comment] 2020-10-16 02:57
Actually this could be done with the discography we have now right @soncaokim ?

**Comment by soncaokim** [comment] 2020-10-16 19:29
With a separate discog and independent tagging code, yes we can start considering this.

However, the issue is there is no universal/accepted convention to express multiple artists that I know of.

- For contemporary music, everything is squeezed in same field, using `featuring` `feat` `feat.` `ft` `ft.` `/` `,` `;` `and` `&` `+` as separator
- For classical/opera, there are `artist`, `album artist`, `composer`, `conductor`, `orchestra`, `lead instrument`, `vocal`, etc that may or may not have separate field.
- itunes uses the `compilation` flag to express multi-artist compilation.

The lack of convention implies that we need to adopt one, and it will not be full proof.

I'm wondering what would be the UI for the user to choose/define a convention, and to provide personalised adjustment to the chosen one.

**Comment by bloomvdomino** [comment] 2020-10-17 08:56
> I tried all of them with `; `, `/ `, and `\\` separator (this last one is creating 2 "Artist" or "Genre" entries when used in Mp3tag). None of them works properly pensive

Actually there is a convention, at least for id3v2.4… The mentioned double-backslash in MP3Tag is actually a NULL value who is written between each value in the field. (https://id3.org/id3v2.4.0-frames, under 4.2 'Text information frames')

**Comment by soncaokim** [comment] 2020-10-17 09:40
Right, there is actually possibility to have multiple values for a tag, and it seems to be a sane approach.

The question now is: how to deal with existing tags (feat ft duet...) The laziest way would be offering the user the UI to tag multiple artists manually 😀

**Comment by bloomvdomino** [comment] 2020-10-17 15:04
I think it would be not that elegant to implement a non-standard way of separating strings based on symbols/words. This solution is very unreliable (think about 'AC/DC') – as written before.

Therefore I would only implement the NULL separator and the mentioned possibility to add them via UI. Maybe with an '+' button to add an new field to fill each time the button is pressed and a '–' button beside every new field (greater than one) to remove it.

The NULL separator could also be implemented for the ID3v2.3 tag parser, to obtain backwards compatibility and consistency. But this is debatable, because it's non-standard, even if brings no disadvantages.

**Comment by soncaokim** [comment] 2021-01-13 18:06
To follow up on this: I've attempted an implementation here - https://github.com/AdrienPoupa/VinylMusicPlayer/pull/345

To keep the expectation low :-)
- it's based on the ';' to separate different artists.
- there are still works to do behind the scene to keep the library consistent.
- no UI change yet to support add/remove artists

However I'm using this daily on my library, and it's acceptable.

--

On the separator vs null value debate: 

another thing to consider is the compatibility with other music players. Using a dumb ';' makes the list of artists still visible and modifiable in other clients, while using a null value might induce compat (I havent tested nor investigated).

What's your opinions?

**Comment by sersorrel** [comment] 2021-01-17 19:57
>another thing to consider is the compatibility with other music players. Using a dumb ';' makes the list of artists still visible and modifiable in other clients, while using a null value might induce compat (I havent tested nor investigated).

given the [ID3v2.4 spec](https://id3.org/id3v2.4.0-frames) explicitly supports null-separated strings:

>4.2.   Text information frames
>
>   The text information frames are often the most important frames,
>   containing information like artist, album and more. There may only be
>   one text information frame of its kind in an tag. **All text
>   information frames supports multiple strings, stored as a null
>   separated list, where null is reperesented by the termination code
>   for the charater encoding.** All text frame identifiers begin with "T".

i would really like vinyl to at least _support_ files with null-separated metadata, even if it splits on another character as well.

**Comment by soncaokim** [comment] 2021-01-17 20:58
> i would really like vinyl to at least _support_ files with null-separated metadata, even if it splits on another character as well.

Hey, thanks for the comment.

This is planned (see the todo list in my mentioned pull request).

Even though it's mentioned in the specs, I wonder how widespread is this supported. Since you are requesting, may I know which clients you have seen that support this null character split?

Thanks

**Comment by sersorrel** [comment] 2021-01-18 03:39
[rhythmbox](https://wiki.gnome.org/Apps/Rhythmbox) does not (the [feature request](https://gitlab.gnome.org/GNOME/rhythmbox/-/issues/16) has been open for something like 17 years...); [quod libet](https://quodlibet.readthedocs.io/en/latest/) does. i don't know whether other players do or don't support it, sorry.

[kid3](https://kid3.kde.org/) is capable of creating null-separated lists of strings in tags by entering `|` as the delimiter.

it might be worth noting that, although rhythmbox doesn't _support_ multi-artist tracks, all that happens if you load an mp3 with a multi-value id3v2.4 string tag is that it displays the first string (e.g. if i tagged [kei](https://anamanaguchi.bandcamp.com/track/kei-featuring-pochi) as being by `anamanaguchi|pochi` in kid3, rhythmbox would just display "anamanaguchi") – it doesn't crash or fail in other ways, so using an id3v2.4 library works fine for the most part.

**Comment by soncaokim** [comment] 2021-01-18 10:36
> it doesn't crash or fail in other ways, so using an id3v2.4 library works fine for the most part.

I think this is supported already with the current released version (havent tested though). If you spot a problem with that, please let me know.

**Comment by soncaokim** [comment] 2021-02-12 20:43
Multiple artist is supported in version 1.1.0.
I'm closing this for now, please dont hesitate to reopen (or create a new one) if the proposed solution is not satisfactory.

**Closed by soncaokim** 2021-02-12 20:43 UTC
Labels: feature request
