### ISSUE TITLE
Tapping a certain part of the app crashes it.

### ISSUE THREAD

**Issue by Some1ls** [AdrienPoupa/VinylMusicPlayer#490] opened 2021-07-11 22:21 UTC
**Describe the bug**
Tapping the part just below the header of the playlist (the one with the clock) crashes the app.

![image_6656_llcrop](https://user-images.githubusercontent.com/64040417/125211229-83ae0d00-e2d7-11eb-862a-a194b238546a.jpg)
![image_6658_llcrop](https://user-images.githubusercontent.com/64040417/125211239-91fc2900-e2d7-11eb-9ed7-d97e2cfeff5a.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A11
 - Android Version: Android 11
 - ROM: One UI
 - Vinyl Music Player Version: 1.3.0 from play store

**Additional context**

**Comment by soncaokim** [comment] 2021-07-11 22:33
This should be a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/485

**Closed by soncaokim** 2021-07-11 22:33 UTC
Labels: bug
