### ISSUE TITLE
Separate artists in a song

### ISSUE THREAD

**Issue by ghost** [AdrienPoupa/VinylMusicPlayer#52] opened 2018-05-27 23:25 UTC
Separate artists in the tag editor with ";" so the song appears in both artist's pages in the case a single track has multiple artists.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.17.0</td></tr>
<tr><td>App version code</td><td>155</td></tr>
<tr><td>Android build version</td><td>J700MUBS2BQB2</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.J700MUBS2BQB2</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j7elte</td></tr>
<tr><td>Device model</td><td>SM-J700M</td></tr>
<tr><td>Device product name</td><td>j7elteub</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7580</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by Cantuariensis** [comment] 2020-08-15 10:36
Duplicate of #207, which is more detailed.

@AdrienPoupa @soncaokim Can you close this one?

**Closed** 2020-08-16 12:42 UTC
Labels: feature request
