### ISSUE TITLE
Crash when grabbing the scrollbar from the top in a playlist's view

### ISSUE THREAD

**Issue by Uvik** [AdrienPoupa/VinylMusicPlayer#565] opened 2022-01-10 10:36 UTC
**Describe the bug**
When in a playlist view, the app deterministically crashes when I try to grab the scrollbar from the top on the list. 
If I scroll a bit with my finger beforehand, I can grab the scrollbar and move it everywhere, including to the top, without causing the app to crash. But if I drag it back to the top and try to move it from here, the app crashes too.

**To Reproduce**
1. Go to the "Playlists" tab
2. Open a playlist that has enough tracks to make it scrollable (9+ tracks on my device)
3. Drag the scrollbar when it is at the top of the list. The app immediately crashes.

**Screenshots**
I captured the crash in video, also showing that grabbing the scrollbar from the top works in "Songs" and "Albums" tabs:
https://user-images.githubusercontent.com/11810912/148751602-058a1ad5-150b-4751-bb9b-84acbcc6381a.mp4

**Smartphone (please complete the following information):**
- Device: OnePlus 7 Pro (GMT1913)
- Android Version: 11
- ROM: Oxygen OS 11.0.3.1.GM21BA
- Vinyl Music Player Version: 1.3.0 (Google Play Store)

**Comment by soncaokim** [comment] 2022-01-19 21:07
Hi, thanks for the effort to report this. I've tried reproducing the error without success.

To give me more information: 
- Can you please tell how you created the "Favoris" playlist demoed in the video - i.e. create a new playlist via the app, or a playlist created by another app on your device? 
- Any particular note on the songs listed in the playlist?
- Is this happening to the static playlists, or to the dynamic ones as well (i.e. History / Not Recently played / Top tracks)?

**Comment by soncaokim** [comment] 2022-02-12 08:34
Closing this, I am unable to reproduce.
Please dont hesitate to reopen the issue if there is any further information

**Closed by soncaokim** 2022-02-12 08:34 UTC
Labels: bug
