### ISSUE TITLE
Ogg/Opus: Track numbers all start with 1000

### ISSUE THREAD

**Issue by nermolov** [AdrienPoupa/VinylMusicPlayer#397] opened 2021-03-28 19:55 UTC
**Describe the bug**
Track numbers all start with 1000. See screenshot further down

**To Reproduce**
1. Open any album and look at the track numbers
2. Note that they start with 1000

**Expected behavior**
Normal track numbers.

**Screenshots**
![Screenshot_20210328-155140](https://user-images.githubusercontent.com/6175137/112766014-d4765000-8fdd-11eb-879a-f7aef77f7108.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - Android Version: 11
 - ROM: Stock
 - Vinyl Music Player Version: 1.1.2

**Comment by soncaokim** [comment] 2021-03-28 20:11
- Can you please explain since when this behavior is observed (are you just upgraded to version 1.1.2 from previous pre-1.0.0 version)?
- If you open the tag editor for the track, do you see the track number as 1007, or as 7 (with disc number being 1)?

My guess: this is linked with the (weird) convention from Android MediaStore where the track number is combined with disc number, i.e. 1007 means 'disc 1, track 7'. I've removed the support for this recently, as during my tests it is not needed anymore.

**Comment by nermolov** [comment] 2021-03-31 02:28
> Can you please explain since when this behavior is observed (have you just upgraded to version 1.1.2 from previous pre-1.0.0 version)?

I've been upgrading every version on F-Droid consistently since before 1.0.0

> If you open the tag editor for the track, do you see the track number as 1007, or as 7 (with disc number being 1)?

Opening the tag editor shows no info in any fields. The files are ogg/opus if that helps.

**Comment by soncaokim** [comment] 2021-03-31 17:18
Thanks for the clarification. I'm changing the title of this bug report to mention the fact that this concerns Ogg/Opus.

This app relies on the jaudiotagger lib for metadata extraction and edition, and fallbacks on Android OS if the lib does not support it.

I have no experience on the format, but based on the reports I guess that the lib does not support it.

We need to have it fixed it in the upstream, or we use another lib with richer support.

**Comment by soncaokim** [comment] 2021-03-31 19:51
> I have no experience on the format, but based on the reports I guess that the lib does not support it.

https://bitbucket.org/ijabz/jaudiotagger/issues/65/add-support-for-ogg-opus-format
https://community.jthink.net/t/opus-tagging-support/9628

@AdrienPoupa  There is some recent changes on the library: https://bitbucket.org/ijabz/jaudiotagger/src/master/CHANGES.txt
Are they worth updating?

**Comment by AdrienPoupa** [comment] 2021-04-01 15:17
Yes I guess they are, good point!

**Comment by soncaokim** [comment] 2021-04-01 20:34
@nermolov Is that possible to post a copy of ogg/opus track of your own, to help reproducing the issue on my end (and eventually I can make sure that the 100x prefix is removed).

For proper support of Ogg/Opus, as mentioned above, someone needs to step in and fixes it upstream.

**Comment by nermolov** [comment] 2021-04-05 13:54
Here's an opus file demonstrating the issue: https://nermolov.com/song.opus (github wouldn't let me attach it).

Encoded from FLAC with `opusenc`.

**Comment by soncaokim** [comment] 2021-04-05 19:05
Thanks for the sample. It looks ok on my end

![Screenshot_20210405-205953~2](https://user-images.githubusercontent.com/13333482/113614260-91a61f00-9652-11eb-836e-aa91a121f594.jpg)

**Comment by nermolov** [comment] 2021-04-05 19:18
Huh odd, I'll try building from git rather than F-Droid and see.

**Comment by soncaokim** [comment] 2021-04-05 19:51
> Huh odd, I'll try building from git rather than F-Droid and see.

I dont think that would help. As explained above, in this case I guess the metadata extraction is provided by the OS and MediaStore provider.

**Comment by nermolov** [comment] 2021-04-05 20:20
In what case is MediaStore/OS used vs VMP internal library?

**Comment by soncaokim** [comment] 2021-04-05 21:14
>  This app relies on the jaudiotagger lib for metadata extraction and edition, and fallbacks on Android OS if the lib does not support it.

Given that the tag editor screen is empty, this implies the lib does not support it.

**Comment by soncaokim** [comment] 2021-04-05 21:16
And if want to know the exhaustive list of encoding supported, you need to search for relevant info on the mentioned lib.

**Comment by soncaokim** [comment] 2021-06-03 20:16
Closing this as it's not reproducible on my end. Please dont hesitate to reopen with additional info.

**Closed by soncaokim** 2021-06-03 20:16 UTC
Labels: bug, can't reproduce
