### ISSUE TITLE
add following system theme support

### ISSUE THREAD

**Issue by Jacky486** [AdrienPoupa/VinylMusicPlayer#430] opened 2021-04-28 00:30 UTC
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add system theme support for better usage.

**Describe alternatives you've considered**

**Additional context**

**Comment by soncaokim** [comment] 2021-05-08 20:17
Closing this, duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/406

**Closed by soncaokim** 2021-05-08 20:17 UTC
Labels: feature request
