### ISSUE TITLE
[Crash] Album Artwork Issue

### ISSUE THREAD

**Issue by fapping-wolf** [AdrienPoupa/VinylMusicPlayer#33] opened 2018-05-03 03:21 UTC
App crashes when attempting to save albums after applying artwork from last.fm

**Comment by AdrienPoupa** [comment] 2018-05-03 05:36
Hi,

Could you provide some logs?

**Comment by GeoZac** [comment] 2018-05-03 09:07
@AdrienPoupa  `java.lang.NullPointerException: Attempt to invoke virtual method 'com.poupa.vinylmusicplayer.lastfm.rest.model.LastFmAlbum$Album com.poupa.vinylmusicplayer.lastfm.rest.model.LastFmAlbum.getAlbum()' on a null object reference`

**Comment by fapping-wolf** [comment] 2018-05-04 03:02
[logcatforcrash.txt](https://github.com/AdrienPoupa/VinylMusicPlayer/files/1973201/logcatforcrash.txt)

I grabbed this logcat earlier, if you want me to grab something more specific please let me know.

**Comment by AdrienPoupa** [comment] 2018-05-04 03:29
Thanks, I'll have a look

**Comment by AdrienPoupa** [comment] 2018-05-04 23:44
Hi, what version are you using?

I can download the album art from Last.fm and save it without any issue on latest 0.17.0.

**Comment by fapping-wolf** [comment] 2018-05-05 02:31
Currently also on 0.17.0

**Comment by Sirbu** [comment] 2018-05-07 13:14
I also have the same problem while attempting to save album after loading artwork from storage.

**Comment by AdrienPoupa** [comment] 2018-05-09 15:13
Hi, I'm not sure I understand the bug. You try to edit an album, select the Last.fm option and save it, right? As you can see I'm not having any issue doing it

![ezgif com-resize](https://user-images.githubusercontent.com/15086425/39799912-0062d0a6-5334-11e8-8c27-e8ab1b73f7e9.gif)

**Comment by fapping-wolf** [comment] 2018-05-09 20:03
I follow same steps you took however as soon as the progress dialogue box opens the app crashes. Also as far as I can tell this bug only affects albums without any artwork present, replacing album covers seems to work fine.

**Comment by sunnichan** [comment] 2018-07-04 11:36
Hi, iam still having this error. Cant update album art from last.Fm or from local storage

**Comment by devtons** [comment] 2018-07-06 09:36
Hello, I have the same error as sunnichan explained.

**Comment by Tmplt** [comment] 2019-01-26 02:03
Issue present in 0.18.0.

Log for fetching art via Last.fm:
```
01-26 02:54:51.842 W/System.err(32458): 	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source)
01-26 02:54:51.842 W/System.err(32458): 	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source)
01-26 02:54:51.885 E/AndroidRuntime(32458): Process: com.poupa.vinylmusicplayer, PID: 32458
01-26 02:54:51.890 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.tageditor.AlbumTagEditorActivity
01-26 02:54:52.398 W/ActivityManager(5269): Activity pause timeout for ActivityRecord{454e345 u0 com.poupa.vinylmusicplayer/.ui.activities.tageditor.AlbumTagEditorActivity t6202 f}
01-26 02:54:54.008 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.tageditor.AlbumTagEditorActivity
01-26 02:54:54.018 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.AlbumDetailActivity
01-26 02:54:54.023 E/ActivityManager(5269): Found activity ActivityRecord{26e62d7 u0 com.poupa.vinylmusicplayer/.ui.activities.AlbumDetailActivity t6202 f} in proc activity list using null instead of expected ProcessRecord{917da3 32458:com.poupa.vinylmusicplayer/u0a72}
01-26 02:54:54.030 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.ArtistDetailActivity
01-26 02:54:54.031 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.SearchActivity
01-26 02:54:54.031 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.MainActivity
01-26 02:54:54.031 E/ActivityManager(5269): Found activity ActivityRecord{4003ace u0 com.poupa.vinylmusicplayer/.ui.activities.MainActivity t6202 f} in proc activity list using null instead of expected ProcessRecord{917da3 32458:com.poupa.vinylmusicplayer/u0a72}
01-26 02:54:54.032 E/ActivityManager(5269): Found activity ActivityRecord{6ff020f u0 com.poupa.vinylmusicplayer/.ui.activities.SearchActivity t6202 f} in proc activity list using null instead of expected ProcessRecord{917da3 32458:com.poupa.vinylmusicplayer/u0a72}
01-26 02:54:54.032 E/ActivityManager(5269): Found activity ActivityRecord{79efc u0 com.poupa.vinylmusicplayer/.ui.activities.ArtistDetailActivity t6202 f} in proc activity list using null instead of expected ProcessRecord{917da3 32458:com.poupa.vinylmusicplayer/u0a72}
01-26 02:54:54.032 I/ActivityManager(5269): Killing 32458:com.poupa.vinylmusicplayer/u0a72 (adj 0): crash
```

Log when using a local image:
```
01-26 02:57:33.791 W/DocumentsActivity(32276): Failed to restore stack for package: com.poupa.vinylmusicplayer because of error: java.io.FileNotFoundException: Failed to find matching root for null
01-26 02:57:36.673 W/System.err(911): 	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source)
01-26 02:57:36.673 W/System.err(911): 	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source)
01-26 02:57:36.752 E/AndroidRuntime(911): Process: com.poupa.vinylmusicplayer, PID: 911
01-26 02:57:36.755 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.tageditor.AlbumTagEditorActivity
01-26 02:57:37.262 W/ActivityManager(5269): Activity pause timeout for ActivityRecord{2611d9 u0 com.poupa.vinylmusicplayer/.ui.activities.tageditor.AlbumTagEditorActivity t6218 f}
01-26 02:57:38.508 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.tageditor.AlbumTagEditorActivity
01-26 02:57:38.514 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.AlbumDetailActivity
01-26 02:57:38.516 E/ActivityManager(5269): Found activity ActivityRecord{3fc8b16 u0 com.poupa.vinylmusicplayer/.ui.activities.AlbumDetailActivity t6218 f} in proc activity list using null instead of expected ProcessRecord{c2d66f6 911:com.poupa.vinylmusicplayer/u0a72}
01-26 02:57:38.525 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.ArtistDetailActivity
01-26 02:57:38.525 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.SearchActivity
01-26 02:57:38.526 W/ActivityManager(5269):   Force finishing activity com.poupa.vinylmusicplayer/.ui.activities.MainActivity
01-26 02:57:38.527 E/ActivityManager(5269): Found activity ActivityRecord{6e66046 u0 com.poupa.vinylmusicplayer/.ui.activities.MainActivity t6218 f} in proc activity list using null instead of expected ProcessRecord{c2d66f6 911:com.poupa.vinylmusicplayer/u0a72}
01-26 02:57:38.527 E/ActivityManager(5269): Found activity ActivityRecord{2d70d3a u0 com.poupa.vinylmusicplayer/.ui.activities.SearchActivity t6218 f} in proc activity list using null instead of expected ProcessRecord{c2d66f6 911:com.poupa.vinylmusicplayer/u0a72}
01-26 02:57:38.527 E/ActivityManager(5269): Found activity ActivityRecord{6be05af u0 com.poupa.vinylmusicplayer/.ui.activities.ArtistDetailActivity t6218 f} in proc activity list using null instead of expected ProcessRecord{c2d66f6 911:com.poupa.vinylmusicplayer/u0a72}
01-26 02:57:38.528 I/ActivityManager(5269): Killing 911:com.poupa.vinylmusicplayer/u0a72 (adj 0): crash
01-26 02:57:38.602 W/InputDispatcher(5269): channel '6e027c9 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-26 02:57:38.602 E/InputDispatcher(5269): channel '6e027c9 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-26 02:57:38.606 I/WindowManager(5269): WIN DEATH: Window{4dcf295 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.tageditor.AlbumTagEditorActivity}
01-26 02:57:38.610 I/WindowManager(5269): WIN DEATH: Window{6a1aff4 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.SearchActivity}
01-26 02:57:38.613 I/WindowManager(5269): WIN DEATH: Window{4451cc1 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.ArtistDetailActivity}
01-26 02:57:38.617 I/WindowManager(5269): WIN DEATH: Window{eeedef0 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.AlbumDetailActivity}
01-26 02:57:38.620 I/WindowManager(5269): WIN DEATH: Window{6e027c9 u0 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity}
01-26 02:57:38.620 W/InputDispatcher(5269): Attempted to unregister already unregistered input channel '6e027c9 com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.MainActivity (server)'

```

**Comment by AdrienPoupa** [comment] 2019-01-26 14:39
Hi @Tmplt 

Thanks for the report. That's a bug I'd like to fix, unfortunately I'm still unable to reproduce it.

Your logs could help, though. Could you also share a recording of your screen until the failure or a detailed list of steps? Also, what's your device and Android version? Are you using a ROM?

Thanks again!

**Comment by Tmplt** [comment] 2019-01-26 18:09
@AdrienPoupa steps are simple:
1. Enter the tag editor for an album that does not have a cover already.
2. Press-and-hold the album image placeholder, release and select an image either via the file manager or via Last.fm.
3. Press the save icon in the lower right.
4. Observe crash.

I'm running LineageOS 14.1, Android 7.1.2, on an Xiaomi Redmi Note 3 (kenzo).

**Comment by Tmplt** [comment] 2019-01-26 20:17
I do have a SD card. The bug is reproducible with albums both on the SD card and not.

**Comment by AdrienPoupa** [comment] 2019-01-26 21:49
OK, I have committed a fix for writing on the SD card, but I'm really surprised that it also happens on the internal storage :(

**Comment by soncaokim** [comment] 2020-01-23 21:14
Shouldnt we close this bug report, given that LastFM is no longer an option?

**Closed** 2020-01-24 00:19 UTC
Labels: bug

**Comment by daemonspudguy** [comment] 2021-05-05 15:58
It's still an issue with album art from local storage.
