### ISSUE TITLE
Crashes when reaching the "M" on the artist tab

### ISSUE THREAD

**Issue by nalexcastaneda** [AdrienPoupa/VinylMusicPlayer#215] opened 2019-11-27 04:32 UTC
So I was scrolling in the artist tab using the app's scrollbar and it suddenly crashed. This happened also when I scroll manually with my fingers. This issue also happens in my tablet. I am using Android 9

-

Device info:
---
<table>
<tr><td>App version</td><td>0.22.1</td></tr>
<tr><td>App version code</td><td>167</td></tr>
<tr><td>Android build version</td><td>126371b462</td></tr>
<tr><td>Android release version</td><td>9</td></tr>
<tr><td>Android SDK version</td><td>28</td></tr>
<tr><td>Android build ID</td><td>PQ3A.190801.002</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>cedric</td></tr>
<tr><td>Device model</td><td>XT1671</td></tr>
<tr><td>Device product name</td><td>aosp_cedric</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by AdrienPoupa** [comment] 2020-01-18 18:16
Duplicate of #166

**Closed by AdrienPoupa** 2020-01-18 18:16 UTC
