### ISSUE TITLE
Vinyl 0.22 / 0.22.1 crashes when scrolling through artist list 

### ISSUE THREAD

**Issue by Tom4tot** [AdrienPoupa/VinylMusicPlayer#166] opened 2019-05-18 02:32 UTC
**Describe the bug**
If I set on "auto download metadata", when I scroll quickly through the artists list, the app crashes every time. It happens since 0.22 update and 0.22.1 didn't fix it.

No issues on other lists.

No issues if I turn off the option.

I have a big library (around 40GB so maybe that's why)

I'm attaching two logs in case you can't reproduce the issue.

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - Android Version: Pie
 - ROM: Omnirom

Thanks for your work and the updates.
[2019-05-18-12-20-36.txt](https://github.com/AdrienPoupa/VinylMusicPlayer/files/3193565/2019-05-18-12-20-36.txt)
[2019-05-18-12-16-27.txt](https://github.com/AdrienPoupa/VinylMusicPlayer/files/3193566/2019-05-18-12-16-27.txt)

**Comment by soncaokim** [comment] 2019-05-18 08:02
The logs points to

https://github.com/AdrienPoupa/VinylMusicPlayer/blob/dbaedfadf8a3dcf9966dcfa82107c092432aefb1/app/src/main/java/com/poupa/vinylmusicplayer/glide/artistimage/ArtistImageFetcher.java#L71

Probably @paolovalerdi you may want to add an extra check on the returned list?

**Comment by paolovalerdi** [comment] 2019-05-18 12:39
@soncaokim Yes I just saw it's a NPE

**Comment by AdrienPoupa** [comment] 2019-05-18 15:24
Weird I can't reproduce it on my device, bit thanks for the confirmation guys.

@paolovalerdi can you make a PR? So that I can release a new version quickly after that

**Comment by paolovalerdi** [comment] 2019-05-18 16:02
@AdrienPoupa I can't reproduce it neither, that's why I didn't notice it. I will make the PR later today.

**Comment by soncaokim** [comment] 2019-05-18 16:04
Just keep frantically scrolling the artist view 😋

**Comment by AdrienPoupa** [comment] 2019-05-18 16:09
Even doing so it doesn't crash for me. What's your grid layout?

**Comment by soncaokim** [comment] 2019-05-18 16:19
It s a 3

**Comment by Tom4tot** [comment] 2019-05-19 00:11
My grid size is 1.

Maybe try to clear the app's data and try again because if your app already cached all the images the bug might not happen.

Anyway, thanks for your interest in this issue.

**Comment by soncaokim** [comment] 2019-05-21 19:34
I'm closing this, assuming the fix gets released in the upcoming version.
@Tom4tot / @paolovalerdi Feel free to reopen if the bug persists.

**Closed by soncaokim** 2019-05-21 19:34 UTC
Labels: bug, reproduced
