### ISSUE TITLE
Albums missing years

### ISSUE THREAD

**Issue by pennbauman** [AdrienPoupa/VinylMusicPlayer#240] opened 2020-04-10 09:55 UTC
Ransoms albums will display as if they have no year ("..." inn place of a year), but when I go into the tag editor to add one it is already there.

-

Device info:
---
<table>
<tr><td>App version</td><td>0.23.1</td></tr>
<tr><td>App version code</td><td>168</td></tr>
<tr><td>Android build version</td><td>6254899</td></tr>
<tr><td>Android release version</td><td>10</td></tr>
<tr><td>Android SDK version</td><td>29</td></tr>
<tr><td>Android build ID</td><td>QQ2A.200405.005</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>blueline</td></tr>
<tr><td>Device model</td><td>Pixel 3</td></tr>
<tr><td>Device product name</td><td>blueline</td></tr>
<tr><td>Device hardware name</td><td>blueline</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by soncaokim** [comment] 2020-08-07 22:21
Duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/72

**Closed by soncaokim** 2020-08-07 22:21 UTC
