### ISSUE TITLE
I cannot add songs to the playlists

### ISSUE THREAD

**Issue by helenelax** [AdrienPoupa/VinylMusicPlayer#564] opened 2022-01-07 11:23 UTC
**Describe the bug**
I can create playlists, but when I add songs, they don't appear in the playlist.

**To Reproduce**
I put myself on the song, and I choose "Add to a playlist...", the list of playlists appears, I choose one, I have no error message but my playlist remains empty. I can create several playlists, but they remain empty.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S5 (SM-G900F)
 - Android Version: 11
 - ROM: LineageOS 18.1
 - Vinyl Music Player Version: 1.3.0 (F-Droid)

**Comment by soncaokim** [comment] 2022-01-19 21:09
Are your songs on the SD card?

**Comment by helenelax** [comment] 2022-01-20 09:20
yes

**Comment by soncaokim** [comment] 2022-02-12 08:40
I believe this is a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248, which has no resolution.

**Comment by dp0s** [comment] 2022-05-29 02:02
I have the same issue on lineage os 18.1. and it is indeed very annoying. It seems to be a basic mistake in the android system??

**Comment by openmindednewby** [comment] 2022-07-04 20:23
Hi guys, same here. I can't add songs to the playlists if the playlists are stored on the SD card. Should we close this thread and re-open this one  [#248 ](https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248) :)?

**Closed** 2022-11-27 22:27 UTC
Labels: bug, wontfix
