### ISSUE TITLE
[Feature Request] Gapless playback

### ISSUE THREAD

**Issue by HardCode4All** [AdrienPoupa/VinylMusicPlayer#111] opened 2019-02-26 07:40 UTC
Would it be possible to introduce a gapless playback mode? When you listen to live albums, it is quite annoying that there is a ~1s gap between the songs.

**Comment by AdrienPoupa** [comment] 2019-02-26 16:47
Duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/105

**Closed by AdrienPoupa** 2019-02-26 16:47 UTC
