### ISSUE TITLE
.opus metadata appears blank in editor

### ISSUE THREAD

**Issue by keithhacks** [AdrienPoupa/VinylMusicPlayer#433] opened 2021-05-02 05:40 UTC
**Describe the bug**
.opus file metadata is mostly read fine (the release year is always blank, but everything else is there), but disappears inside the tag editor.

**To Reproduce**
1. Get an Ogg Opus music file and tag it, then copy it to your phone's music folder.
2. Open Vinyl Music Player and navigate to the album.
3. Album art appears fine, but the year is missing.
4. Select '...' -> 'tag editor' on the album or any track.
5. All fields are blank, despite the album, artist, track name, cover art, etc. appearing correctly in the library.

**Expected behavior**
The tag editor should have been able to read the Ogg Opus metadata, especially since the library view had no trouble doing so.

**Smartphone (please complete the following information):**
 - Device: moto g8 power
 - Android Version: Android 11
 - ROM:
 - Vinyl Music Player Version: 1.2.0

**Additional context**

**Comment by soncaokim** [comment] 2021-05-03 18:37
Should be a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/338

**Closed by soncaokim** 2021-05-03 18:37 UTC
Labels: bug
