### ISSUE TITLE
Unable to add music from SD Card to a Playlist

### ISSUE THREAD

**Issue by Zak-Bahm** [AdrienPoupa/VinylMusicPlayer#446] opened 2021-05-14 13:45 UTC
**Describe the bug**
If a song is stored in a removable sd card it cannot be added to a playlist. You can try to favorite it or add it to any other playlist but it won't be added.

**To Reproduce**
1. Find a song that is currently stored on your sd card
2. Click on Heart icon to favorite it
3. Check the favorites playlist to verify it isn't there

**Expected behavior**
Songs should be added to any playlist you attempt to add them to.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Note 9
 - Android Version: 10
 - ROM: Stock
 - Vinyl Music Player Version: 1.2.0

**Comment by soncaokim** [comment] 2021-05-14 16:12
I believe this is a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/248, which has no resolution.

If anyone can come up with a proposal, please dont hesitate to reopen the original bug report.

**Closed by soncaokim** 2021-05-14 16:12 UTC
Labels: bug
