### ISSUE TITLE
Crash in the artist view with specific artist tag

### ISSUE THREAD

**Issue by TomEff** [AdrienPoupa/VinylMusicPlayer#203] opened 2019-10-12 19:49 UTC
**Describe the bug**
Vinyl reproducibly crashes, when I get to a specific point in the artist view list. After a few tests I found the culprit to be one specific artist tag which is "maudlin of the Well". I tried different tag editors, ogg, mp3, but it seems to be said artist tag.
When changing it to e.g. "of the Well" or "maudlin of the" everything is fine.
It also does not happen when wifi/mobile access is disabled so maybe it has something to do with retrieving meta information from the web.

Thanks a lot for your work!!

**To Reproduce**
1. Use any mp3/ogg file and change the artist tag to "maudlin of the Well"
2. update the library
3. scroll down to "maudlin of the Well" in the artist view

**Comment by aricooperdavis** [comment] 2019-10-30 00:13
I too am experiencing this bug. I haven't worked out what the tag is yet, but thank you for highlighting that turning mobile data/WiFi off is a workaround.

**Comment by AdrienPoupa** [comment] 2020-01-18 18:16
Duplicate of #166

**Closed by AdrienPoupa** 2020-01-18 18:16 UTC
Labels: bug
