### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Dastardly-Entrench** [AdrienPoupa/VinylMusicPlayer#466] opened 2021-06-20 06:03 UTC
**Describe the bug**
App crashes when opened

**To Reproduce**
1. Download app from f droid
2. Open app 
3. Try to give storage permission
4. As soon as permission is given App crashes

**Expected behavior**
App should work properly

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: mido
 - Android Version: 7
 - ROM: miui 11
 - Vinyl Music Player Version: latest on f droid

**Additional context**

**Comment by soncaokim** [comment] 2021-06-24 22:19
I'm suspecting this is a duplicate of https://github.com/AdrienPoupa/VinylMusicPlayer/issues/445.

Please dont hesitate to reopen this issue if the new version is not fixing it.

**Closed by soncaokim** 2021-06-24 22:19 UTC
Labels: bug
